### ISSUE TITLE
Consider moving to GNOME Gitlab

### ISSUE THREAD

**Issue by jbicha** [Hjdskes/gcolor3#105]
Would you be interested in moving this project to GNOME infrastructure?

https://gitlab.gnome.org/World

**Comment by jbicha** [comment]
The wiki says you should talk to https://wiki.gnome.org/CarlosSoriano

**Comment by Hjdskes** [comment]
Thanks, email sent.

**Comment by Hjdskes** [comment]
This is now done: https://gitlab.gnome.org/World/gcolor3/

I'll leave this repository active for now, so current contributors will see the move and have time to move as well or send in their last pull requests.
