### ISSUE TITLE
Create a PPA for Ubuntu

### ISSUE THREAD

**Issue by ghost** [Hjdskes/gcolor3#21]
Hello,

To ease the installation of this very useful application is it possible that you create a PPA for Ubuntu ?

Thank you

**Comment by Unia** [comment]
I have never looked into how PPA's work and such, so I have no clue how much work it is going to be. It is something I might look at in the future, but don't expect anything anytime soon. If someone with the knowledge and willingness to create a PPA for gcolor3 comes across this: feel free to set it all up. Let me know if I can help with something :)

**Comment by Paviluf** [comment]
Ok I understand. However, if you want read some infos about creating a ppa, this link can be insteresting :
https://help.launchpad.net/Packaging/PPA

I really think it's important to be able to easily install the app.

**Comment by Paviluf** [comment]
Maybe you could ask to varlesh some infos to create the PPA :
https://launchpad.net/~varlesh-l

He offers a gcolor3 build for Trusty
https://launchpad.net/~varlesh-l/+archive/ubuntu/gtk3-apps

**Comment by Unia** [comment]
Thanks for the links. I am quite busy in the foreseeable future so again, don't expect anything anytime soon. It's not that hard to locally create a .deb package and install that, though. (Altho I understand that a PPA might be easier for some). Is there anything specific that is not working that I might be able to assist you with?

**Comment by Paviluf** [comment]
> don't expect anything anytime soon.

I don't ;)

> Is there anything specific that is not working that I might be able to assist you with?

Thank you but I have no problem to install it

> PPA might be easier for some

I just prefer use a PPA (auto update, etc...) and I think it's a shame that some really good/useful softs exist on Linux and there is no way to find and install them easily.

**Comment by Paviluf** [comment]
Still no interest for a Ubuntu PPA ?

**Comment by Unia** [comment]
Noone has stepped forward, no.

**Comment by khurshid-alam** [comment]
Deb is available at https://launchpad.net/~varlesh-l/+archive/ubuntu/ubuntu-tools

**Comment by Unia** [comment]
Thanks! Do you know how fast they respond to updates?

**Comment by khurshid-alam** [comment]
@Hjdskes If you want to setup your daily-build ppa I can help you with that.

**Comment by Hjdskes** [comment]
@khurshid-alam I do not want to maintain such a ppa myself and besides, daily builds for Gcolor3 are unnecessary since it is not regularly updated. Thanks for the offer, though.

**Comment by evertiro** [comment]
I'm now maintaining a PPA for this (currently Bionic only, will add others on request)
https://launchpad.net/~evertiro/+archive/ubuntu/gcolor3

**Comment by Hjdskes** [comment]
Cool, thanks. Note that I will release version 2.3 next week, see #98.

**Comment by Hjdskes** [comment]
Since there is a PPA now, I will close this issue now. Please contact @evertiro for problems with the PPA.
