### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by orschiro** [Hjdskes/gcolor3#54]
![image](https://cloud.githubusercontent.com/assets/170947/20625514/14a46848-b314-11e6-8f3f-69dea805cf47.png)

![image](https://cloud.githubusercontent.com/assets/170947/20625516/1851f8e8-b314-11e6-9cdc-f5e0effb6a4c.png)

**Comment by orschiro** [comment]
![image](https://cloud.githubusercontent.com/assets/170947/20625553/587bf220-b314-11e6-9c10-ea4176f8a78d.png)

**Comment by Hjdskes** [comment]
Yes, I changed my username. The new website is located on hjdskes.github.io/projects/gcolor3. I still have to update this and other projects to reflect this. I'm not sure if/how I should backport this change, as well.

**Comment by BobbyBabes** [comment]
Can't you just add a redirect to the ``<head>`` section of the page for now ?
```html
<head>
<meta http-equiv="refresh" content="0; url=http://hjdskes.github.io/projects/gcolor3" />
.
.
.
</head>
```

**Comment by Hjdskes** [comment]
Seems quite unfair towards GitHub to reserve a username just for that purpose. I just need to kick myself into changing those projects. Perhaps one of these days...

**Comment by BobbyBabes** [comment]
You're too honest for this world.
Multiple a/c are allowed as far as I know.

**Comment by Hjdskes** [comment]
The rename has taken place and will be in the upcoming 2.3 release. I'm closing this.
