### ISSUE TITLE
Unknown application name

### ISSUE THREAD

**Issue by orschiro** [Hjdskes/gcolor3#55]
System: Ubuntu 16.10
Version: 2.2. compiled from source

![image](https://cloud.githubusercontent.com/assets/170947/20625606/b4467a76-b314-11e6-8158-341434ff122e.png)

![image](https://cloud.githubusercontent.com/assets/170947/20625609/bf256e48-b314-11e6-9b0b-318d76c0618b.png)

**Comment by Hjdskes** [comment]
Do you happen to know how Unity detects the application name? I set it using `g_set_application_name`: https://github.com/Hjdskes/gcolor3/blob/master/src/gcolor3-application.c#L121

**Comment by orschiro** [comment]
Unfortunately not. :-(

A quick Google Search does not yield any useful results.

https://www.google.es/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=ubuntu+unity+menu+application+name

**Comment by arsaber101** [comment]
The value of the `Name` key in `gcolor3.desktop` file has to be the same as the value of the `Exec` key :

```
[Desktop Entry]
Name=gcolor3
Name[en_US]=Color picker
Name[de_DE]=Farbwähler
Name[en_GB]=Colour picker
...
Exec=gcolor3
...
```

Ref : https://mail.gnome.org/archives/gtkmm-list/2014-November/msg00039.html

**Comment by Hjdskes** [comment]
Thanks for the information! @orschiro Can you test if e.g. Eye of GNOME or Nautilus also display this behavior? [Both](https://git.gnome.org/browse/eog/tree/data/eog.desktop.in.in) [do](https://git.gnome.org/browse/nautilus/tree/data/org.gnome.Nautilus.desktop.in) not have the `Name` key equal to its `Exec` key and I couldn't find any Ubuntu specific patches to change this.

**Comment by orschiro** [comment]
Nautilus shows this: 

![image](https://cloud.githubusercontent.com/assets/170947/21233359/2223bb3c-c2ef-11e6-9959-f1f5d2f85aab.png)

**Comment by Hjdskes** [comment]
So unless my search didn't show the correct patches, there is something else going on here...

**Comment by arsaber101** [comment]
It might be related to a specific Ubuntu/Unity key you find in both Eye of GNOME and Nautilus `.desktop` files, as well as many others `.desktop` files where `Name` and `Exec` are different (evince, gedit, file-roller, gimp, orca, totem). The key is `X-Ubuntu-Gettext-Domain` (for internationalization) but its value are always the same as the `Exec` key. Evince, for exemple :

```
[Desktop Entry]
Name=Document Viewer
Comment=View multi-page documents
Keywords=pdf;ps;postscript;dvi;xps;djvu;tiff;document;presentation;
TryExec=evince
Exec=evince %U
...
X-Ubuntu-Gettext-Domain=evince
```

**Comment by Hjdskes** [comment]
@orschiro Can you try the [unity-name](https://github.com/Hjdskes/gcolor3/tree/unity-name) branch to see if this indeed resolves the issue?

**Comment by orschiro** [comment]
Still the same. :-(

**Comment by Hjdskes** [comment]
What happens if you change `_Name=Color picker` to `_Name=@PACKAGE@` in `data/gcolor3.desktop.in.in`?

**Comment by arsaber101** [comment]
Compiled the unity-name branch on ubuntu 16.10 and it works for me.


![capture du 2016-12-15 23-14-50](https://cloud.githubusercontent.com/assets/14233958/21244309/5d683212-c31d-11e6-954d-ef4cb69f61a0.png)

**Comment by Hjdskes** [comment]
@orschiro Did you `make install` to make the translations available? I think I'm going to merge the `unity-name` branch as it seems to work fine for @arsaber101. If your issue persists we'll have to look into it more.

**Comment by orschiro** [comment]
Alright, go ahead and merge it.

If my error will persist, then I am getting back to you.

Maybe I did just something wrong. :-)

**Comment by Hjdskes** [comment]
ab7e693a1895e27c41c565c832d5cfc780f5d098
