### ISSUE TITLE
CTRL+C not working for color name field

### ISSUE THREAD

**Issue by orschiro** [Hjdskes/gcolor3#56]
Hi @Hjdskes,

The keyboard shortcut CTRL+C does not work for the color name field in version 2.2 on Ubuntu 16.10.

![image](https://cloud.githubusercontent.com/assets/170947/20755072/ee3206ea-b70d-11e6-986c-9d46c111a51e.png)

**Comment by orschiro** [comment]
The menu entry does work. 

![image](https://cloud.githubusercontent.com/assets/170947/20755103/0b262042-b70e-11e6-818d-790792787be4.png)

**Comment by Hjdskes** [comment]
Confirmed. However, this text entry is provided by [GtkColorSelection](https://developer.gnome.org/gtk3/stable/GtkColorSelection.html) and is thus not under my control.

**Comment by orschiro** [comment]
Thank you.

Should I submit a bug report against GtkColorSelection?

**Comment by Hjdskes** [comment]
That won't help as it is a deprecated widget. In fact, I believe it is already removed in what is to be gtk+ 4.0

**Comment by orschiro** [comment]
I see, thank you. I think we can close this issue then.
