### ISSUE TITLE
Ubuntu package

### ISSUE THREAD

**Issue by qwertychouskie** [Hjdskes/gcolor3#62]
It seems `gcolor2` was removed from the Ubuntu 17.10 repos, it would be nice to have this as a replacement.

**Comment by Hjdskes** [comment]
Packaging gcolor3 isn't up to me; see #21 for a similar issue. Maybe you can bring this up with the Ubuntu packagers, I don't use Ubuntu so I don't know the process of getting things packaged. If there's anything I can do to assist with packaging, let me know!
