### ISSUE TITLE
License of gcolor3: GPLv2 or GPLv2+

### ISSUE THREAD

**Issue by c72578** [Hjdskes/gcolor3#63]
There is a difference between the license in the LICENSE file, which is GPLv2 and some files of the project, which have a license comment on top (GPLv2+):
```
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
```
src/gcolor3-application.h
src/gcolor3-window.h
src/gcolor3-color-store.h
src/main.c
src/gcolor3-application.c
src/gcolor3-color-store.c
src/gcolor3-window.c

Could you please check and harmonize?
Thanks

**Comment by Hjdskes** [comment]
As far as I know this is the correct way to do this. If it's not, can you point me to a source that explains me how to fix that? There is no special LICENSE file for "GPLv2+".

**Comment by c72578** [comment]
Thanks for having a look and confirming "GPLv2+".
