### ISSUE TITLE
Crashes on Color Select on Default Ubuntu 17.10

### ISSUE THREAD

**Issue by ktaylora** [Hjdskes/gcolor3#65]
Builds just fine, but when you go to click on the dropper icon to select a color, it causes gnome to crash.

**Comment by julianrichen** [comment]
Ubuntu 17.10 now uses GNOME with Wayland right? Probably related to #38? If you login using Xorg do you get the crash?

Also you say that GNOME crashes, did you mean to say gcolor or does it really crash GNOME Shell?

**Comment by ktaylora** [comment]
Ah. Yes, it's on Wayland. And this is probably a duplicate of #38. And yeah, it crashes the whole gnome shell.

**Comment by Hjdskes** [comment]
The whole shell is a new one... makes it a bit more pressing. As a single developer of a small package I can't do much though, we depend on someone else to make and implement a protocol that gcolor3 can use.

I suppose if the shell now crashes I should show a warning that gcolor3 doesn't work instead of the color picker.

**Comment by ktaylora** [comment]
That's understandable. It is a cool app, btw. You'd think that the GNOME devs would roll this into the default color chooser interface for Gnome 3. It's a pretty basic tool that just about every web developer will use. But, so it goes. I guess it's screenshots + gimp for getting color hex codes for now. ;-)

**Comment by netzgestaltung** [comment]
I stuck with the xorg session right now - how to contact Gnome Devs?

**Comment by ktaylora** [comment]
@netzgestaltung , https://wiki.gnome.org/Community/GettingInTouch/

**Comment by netzgestaltung** [comment]
i wrote now to the gnome mailing list, lets see what happens

**Comment by netzgestaltung** [comment]
its now here: https://mail.gnome.org/archives/gtk-app-devel-list/2017-October/msg00038.html

**Comment by netzgestaltung** [comment]
this is the answer i got: https://mail.gnome.org/archives/gtk-app-devel-list/2017-October/msg00039.html

does it help in any ways?

**Comment by Hjdskes** [comment]
@ktaylora @netzgestaltung I just pushed a branch [`fix/wayland-crash`](https://github.com/Hjdskes/gcolor3/tree/fix/wayland-crash) where I have imported `GtkColorSelection` from GTK+ into Gcolor3 to make the picker button insensitive when Gcolor3 is running on Wayland. Can you (preferably both) test if this solves the issue for you?

Importing it was coming sooner or later anyway, as the widget has been removed from GTK4. It also gave me a chance to replace the deprecated `GdkColor` with `GdkRGBA`; replacing all other deprecated API within the widget will happen at a later stage if this approach works.

**Comment by r3b311i0n** [comment]
@Hjdskes Works for me; colour picker is disabled and a tooltip pops up.

* Arch Linux
* Gnome 3.26.2
* GTK 3.22.25
* Wayland 1.14.0

**Comment by Hjdskes** [comment]
Thanks @r3b311i0n!

**Comment by netzgestaltung** [comment]
Hi,

i switched to fedora(korora) yesterday and installed via crop repo - i am not used to compile something, so i dont know how to test. Sorry.
