### ISSUE TITLE
Gcolor icon

### ISSUE THREAD

**Issue by netzgestaltung** [Hjdskes/gcolor3#70]
Hi,

i have a SVG  version of the original gcolor2 icon, just in case there can be usage for it, its downloadable here: https://office.netzgestaltung.at/index.php/s/YU4UfU1IrnkZKHx

greets, tom

**Comment by Hjdskes** [comment]
Thanks, but I don't think there's a need for that. I am happy with the current icon, although I am open for improvements. In any case, I don't want to have an icon that is too similar to gcolor2's, which in turn is quite similar, if not identical, to GTK+'s.

**Comment by netzgestaltung** [comment]
i dont need to change the current icon either but i just wanted to share it on the right place, as i dont have any other usage for it ;-)
