### ISSUE TITLE
Picking anywhere gives #FFFFFF

### ISSUE THREAD

**Issue by noscript** [Hjdskes/gcolor3#73]
My setup: x11 + lightdm

**Comment by dasnoopy** [comment]
happens here too, after recent commits on 01/02 Nov : before that date pick color worked fine..
btw, if could help, starting gcolor3 from a terminal session, when pick a color, appear this error: 

`(gcolor3:2006): Gtk-CRITICAL **: gtk_rgb_to_hsv: assertion 'r >= 0.0 && r <= 1.0' failed
`

X11 and gnome 3.26.2 (archlinux).

**Comment by Hjdskes** [comment]
Thanks for the reports, I will look into it.

**Comment by pkkid** [comment]
For what it's worth the code is breaking here; In my case the color red is being passed in with a double value of 6682.000000.

https://github.com/Hjdskes/gcolor3/blob/master/src/gcolor3-color-selection.c#L1711

**Comment by Hjdskes** [comment]
This is fixed in e310a62 thanks to @pkkid :)
