### ISSUE TITLE
Add it to Flathub

### ISSUE THREAD

**Issue by alex285** [Hjdskes/gcolor3#87]
Hello!
Is it possible to add this to Flathub?

**Comment by Hjdskes** [comment]
There is already a Flatpak manifest, but that currently builds from master. If I understand correctly, Flathub requires Flatpaks to build from stable branches or tarballs.

A new release is almost done, but at the moment I have little time to get it completely done. At that point though, we can publish it on Flathub.

**Comment by alex285** [comment]
super! thanks!

**Comment by Hjdskes** [comment]
The new release is now pending only on updated translations, see #98.

**Comment by Hjdskes** [comment]
Pull request opened: https://github.com/flathub/flathub/pull/601

**Comment by Hjdskes** [comment]
Let's track further progress in that PR. Closing.

**Comment by alex285** [comment]
hey @Hjdskes thanks!
https://youtu.be/iwo_TxWtx0E
