### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by TomaszGasior** [Hjdskes/gcolor3#90]
When I tried to install `gcolor3-git` (which uses master) from AUR on Arch Linux:
```
gcolor3-application.c: In function ‘gcolor3_application_action_quit’:
gcolor3-application.c:80:27: error: cast between incompatible function types from ‘void (*)(GtkWidget *)’ {aka ‘void (*)(struct _GtkWidget *)’} to ‘void (*)(void *, void *)’ [-Werror=cast-function-type]
  g_list_foreach (windows, (GFunc) gtk_widget_destroy, NULL);
                           ^
```

**Comment by Fnux** [comment]
Similar to #35. You can use [this patch](https://fedorapeople.org/cgit/fnux/public_git/rpm-gcolor3.git/tree/gcolor3-2.2-cast_error.patch) in the meantime.

**Comment by Hjdskes** [comment]
You mean #85.

**Comment by TomaszGasior** [comment]
Can't you just fix it in the application?

**Comment by Hjdskes** [comment]
Yes, once I get time. This is workaround until then.
