### ISSUE TITLE
Update translations for 2.3.2

### ISSUE THREAD

**Issue by Hjdskes** [Hjdskes/gcolor3#98]
The release of Gcolor3 2.3 is now only blocking on updated translations. I have myself updated those two that I can. It would be great if you could update the translation of your language!

- [ ] Dutch
- [ ] British English
- [ ] German (@2ion, @palob?)
- [ ] Greek (@alex285, @subdee?)
- [ ] Spanish (@xoan?)
- [ ] French (@ngquerol, @Fnux?)
- [ ] Galician (@xoan, @frandieguez?)
- [ ] Norwegian Bokmål (@hrkristian?)
- [ ] Indonesian (@dindinhernawan?)
- [ ] Serbian (@kostich?)
- [ ] Swedish
- [ ] Ukranian (@dankor?)

I will wait a week before I release version 2.3. Don't feel stressed, if your translation doesn't make it in time I will release a 2.3.1 at some point to include it.

**Comment by evertiro** [comment]
Standing by to update the PPA

**Comment by kostich** [comment]
@Hjdskes, updated the sr_RS in pull request #101.

Cheers!

**Comment by subdee** [comment]
@Hjdskes updated Greek translation in #102

**Comment by Hjdskes** [comment]
@evertiro 2.3 is out! This issue now tracks translations for version 2.3.1.

**Comment by Fnux** [comment]
@Hjdskes I will update the french translation within a few days.

**Comment by Hjdskes** [comment]
Closing this as Gcolor3 has moved to GNOME GitLab, where it will now be translated by GNOME's translation teams.
